name: Update Serial Number

on: pull_request

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.12'
      
      - name: Run Python script
        run: |
          cd scripts
          python update-serial.py
          cd ..
      
      - name: Commit files with new serial
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "generated"
          git push



